name: Generate GitHub Trophy
on:
  schedule:
    - cron: '0 0 * * *' # once a day
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  trophy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ryo-ma/github-profile-trophy@v1.0
        with:
          username: richarddushime
          output_path: trophy.svg
          token: ${{ secrets.TROPHY }}
      - name: Commit and push trophy.svg
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add trophy.svg
            git commit -m "Update trophy.svg"
            git push
          fi
